### ISSUE TITLE
autoindex fix

### ISSUE THREAD

**Issue by nburchha** [f321x/webserv-42-core#53]
change autoindex to be called upon calling the route, not when calling route/autoindex/

**Comment by nburchha** [comment]
do not make another route 'autoindex', rather display all the files of the route it have been called on.

**Comment by PaulicStudios** [comment]
fix that [22:51:35]:[DEBUG]    File request: /workspace/config/www/html/asd/test2/to%20dos%20Community%20Server%202024.odt
[22:51:35]:[WARNING]  Failed to open file: /workspace/config/www/html/asd/test2/to%20dos%20Community%20Server%202024.odt gets url decoded right
